### ISSUE TITLE
Build failure on tip

### ISSUE THREAD

**Issue by ColinIanKing** [01org/intel-cmt-cat#24]
Hi there, I'm getting a build failure from the tip of the tree:

Bisected this down to:
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[6e0aedd08383eac2c1a55bba1b65ec85f19b9cff] File layout change to accomodate new tools, features and extensions

cc -L../../../lib -lpqos -I../../../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -g -O2 -Wcast-align -Wnested-externs    allocation_app.c   -o allocation_app
/tmp/cc0jYqxq.o: In function `main':
/home/king/repos/intel-cmt-cat/examples/c/CAT/allocation_app.c:202: undefined reference to `pqos_init'
/home/king/repos/intel-cmt-cat/examples/c/CAT/allocation_app.c:244: undefined reference to `pqos_fini'
/home/king/repos/intel-cmt-cat/examples/c/CAT/allocation_app.c:209: undefined reference to `pqos_cap_get'
/home/king/repos/intel-cmt-cat/examples/c/CAT/allocation_app.c:216: undefined reference to `pqos_cpu_get_sockets'
/tmp/cc0jYqxq.o: In function `set_allocation_class':
/home/king/repos/intel-cmt-cat/examples/c/CAT/allocation_app.c:139: undefined reference to `pqos_l3ca_set'
/tmp/cc0jYqxq.o: In function `print_allocation_config':
/home/king/repos/intel-cmt-cat/examples/c/CAT/allocation_app.c:171: undefined reference to `pqos_l3ca_get'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'allocation_app' failed
make[1]: *** [allocation_app] Error 1
make[1]: Leaving directory '/home/king/repos/intel-cmt-cat/examples/c/CAT'
Makefile:56: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tkanteck** [comment]
Hi Colin,
I admit there was a bit of revolution in the file structure and build files.
What are the steps to reproduce? pull the tip and run "make" at the top level?

**Comment by ColinIanKing** [comment]
I did a pull and make at the top level; I also did a fresh clean clone and get the same issue

**Comment by ColinIanKing** [comment]
..but I can wait until the next tagged release appears and re-try then if need be as I realize the current repo is in a state of flux.

**Comment by tkanteck** [comment]
I just cloned the tip (https://github.com/01org/intel-cmt-cat/commit/b3d6ac624d6a73b73ca1392e2715c5ab78c38845) and I could compile it without errors (make at the top level).
The library is built as DSO now & needs to be installed to make others apps link against it or LD environment has to be modified. I am guessing this change is causing issue in your environment - I am not sure how to replicate it though.

**Comment by tkanteck** [comment]
Interesting ... I can build it successfully on Fedora 20 but it fails on Ubuntu at the very place you pointed. I can reproduce it now so I should be able to fix it soon, too :)

**Comment by tkanteck** [comment]
This is an issue with linking order which perhaps varies on different tool chain versions. Fix for the problem is on its way.

**Comment by tkanteck** [comment]
https://github.com/01org/intel-cmt-cat/commit/a42362813b4c20d0a272d263c945fbb1d5765412 fixes the problem for me. Can you verify, please?

**Comment by ColinIanKing** [comment]
Thanks, this fixes the issue.
